# Generated by Django 4.1.dev20210922131701 on 2021-11-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.post')),
                ('ingredients', models.TextField()),
                ('serves', models.PositiveSmallIntegerField()),
                ('time_to_make', models.PositiveSmallIntegerField()),
            ],
            bases=('home.post',),
        ),
    ]
